name: Build and publish

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: project-pratice-image

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout project
      uses: actions/checkout@v2.5.0
    
    - name: Set up JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: '17'
        distribution: adopt
        
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build a container image
      run: ./gradlew bootBuildImage --imageName=$IMAGE_NAME
      
    - name: Apply lowercase on repository name
    - id: repository
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ github.repository_owner }}

    - name: Tag & publish to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ steps.repository.outputs.lowercase }}/$IMAGE_NAME
        VERSION=latest
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
